language: ruby
sudo: false
cache: bundler
rvm:
  - 2.1.1
bundler_args: --with test
before_script:
  - npm install surge
script:
  - make test
after_success:
  - echo "Branch: $TRAVIS_BRANCH" > ./public/.build
  - echo "SHA: $(git rev-parse HEAD)" >> ./public/build
  - echo "Date: $(date)" >> ./public/build
  - if [ "$TRAVIS_BRANCH" == "surge" ]; then echo "Deploying to surge..."; surge --project ./public --domain https://dev.socrata.com; fi
