language: ruby
sudo: false
cache: bundler
rvm:
  - 2.1.1
bundler_args: --with test
before_script:
  - npm install surge
script:
  - make test
after_success:
  - echo "Branch: $TRAVIS_BRANCH" | tee  ./public/build.txt
  - echo "SHA: $(git rev-parse HEAD)" | tee -a ./public/build.txt
  - echo "Date: $(date)" | tee -a ./public/build.txt
  - test $TRAVIS_BRANCH" == "surge" && surge --project ./public --domain https://dev.socrata.com; fi
