language: ruby
sudo: false
cache: bundler
rvm:
  - 2.1.1
bundler_args: --with test
before_script:
  - npm install surge
script:
  - make test
after_success:
  if [ "$TRAVIS_BRANCH" == "surge" ]; then
    echo "Deploying to surge..."
  - surge --project ./public --domain https://dev.socrata.com
  fi
