destination: public
exclude: [Makefile, Gemfile, Gemfile.lock, .rvmrc, public, sample-code]
splash: false
splash_homepage: false

ga_tracking_code: "UA-9046230-3"

subsite: dev
title: SODA Developers
icon: fa fa-code
github_repo: https://github.com/socrata/dev.socrata.com
contribute: /contributing.html

local_js: 
  - /js/try.js
  - /js/snufflupadata.js

local_css: ["/css/local.css"]

gems:
  - jekyll-redirect-from
