destination: public
exclude: [Makefile, Gemfile, Gemfile.lock, .rvmrc, public, sample-code]
# permalink: pretty
splash: false
splash_homepage: false

ga_tracking_code: "UA-9046230-3"

subsite: dev
title: SODA Developers
icon: fa fa-code
github_repo: https://github.com/socrata/dev.socrata.com
contribute: /contributing.html

flags:
  show_migration: true
  peeper:
    img: '/img/peeper_ndoch.png'
    link: 'http://www.socrata.com/tech-blog-posts/developer-support-for-national-day-of-civic-hacking-2015/'
    delay: 1000

local_js:
  - //cdnjs.cloudflare.com/ajax/libs/mustache.js/0.8.1/mustache.min.js
  - /common/js/purl.js
  - /common/js/try.js
  - /js/snuffleupadata.js
  - /js/github.js
  - /js/external-link.js
  - /js/js.cookie.js
  - /js/peeper.js

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-mentions

# Offline mode plugin
offline: false
